# Generated by Django 2.2.3 on 2020-01-09 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=30)),
                ('modality', models.CharField(choices=[('Presencial', 'Presencial'), ('Semi-Presencial', 'Semi-Presencial'), ('Remota', 'Remota')], max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateTimeField(default=None)),
                ('end_date', models.DateTimeField(default=None)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event_Stage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateTimeField(default=None)),
                ('end_date', models.DateTimeField(default=None)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miApp.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('join_code', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('country', models.CharField(default='Ecuador', max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('names', models.CharField(max_length=50)),
                ('last_names', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField(default=None)),
                ('age', models.IntegerField(default=None)),
                ('country', models.CharField(default='Ecuador', max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miApp.Event_Stage')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miApp.Participant')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('leader', models.CharField(max_length=150)),
                ('creator', models.CharField(max_length=150)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miApp.Event')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miApp.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miApp.Participant')),
            ],
        ),
        migrations.CreateModel(
            name='Event_constraint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miApp.Event')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miApp.Organizer'),
        ),
    ]
