# Generated by Django 2.2.3 on 2020-01-12 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0002_auto_20200110_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, upload_to='miApp/static/images/events'),
        ),
    ]
