# Generated by Django 3.0.2 on 2020-01-18 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0003_auto_20200112_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='leader',
        ),
        migrations.AddField(
            model_name='group',
            name='participants',
            field=models.ManyToManyField(through='miApp.Membership', to='miApp.Participant'),
        ),
        migrations.AddField(
            model_name='participant',
            name='notification_subscriptions',
            field=models.ManyToManyField(through='miApp.Notification', to='miApp.Event_Stage'),
        ),
        migrations.AlterField(
            model_name='event',
            name='availability',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='event_constraint',
            name='max_group_size',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='event_constraint',
            name='max_participant_age',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='event_constraint',
            name='min_group_size',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='event_constraint',
            name='min_participant_age',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='event_stage',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event_stage',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='group',
            name='status',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='status',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='participant',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='participant',
            name='status',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
